"""init

Revision ID: e2ef2e05186e
Revises: 
Create Date: 2025-02-11 21:33:42.029237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ef2e05186e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('nick_name', sa.String(length=25), nullable=False),
    sa.Column('status', sa.Enum('ALIVE', 'SOLD', 'UNKNOW', name='animalstatusenum'), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='animalsexenum'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals')
    # ### end Alembic commands ###
